### ISSUE TITLE
Allow Videos to Have a Specific Start Time

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#170]
Diego already completed this pull request
https://github.com/livingtongues/living-dictionaries/pull/168

**Comment by jacob-8** [comment]
@AnnaLuisaD - I added a few more changes for @Danble to review and then this will be complete. Do note that when an issue is done, if a PR hasn't already closed it automatically, then close the issue and let the project board automatically move it to the done column. Otherwise we will have "Open" issues in the "Done" column which is confusing.

**Comment by jacob-8** [comment]
#174 closes
