### ISSUE TITLE
Babanki design requests

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#187]
I will update this issue more in the coming days with the exact info.
- They request a change in the List View (please add Babanki Example Sentence and English Example Sentence)
- They request a change to the order of items that appear in Entry view, once the "Plural form" field has been added.

**Comment by AnnaLuisaD** [comment]
Here are the remaining details, below. @Danble let me know if you have questions.

1. Once the Plural form field is available on the platform, please activate it for Babanki. 

2. Please take all the Babanki data that is currently in the "Notes" section, remove it from Notes, and put it in the new Plural Form data field. In case you need to see that exact data in the Babanki spreadsheet, here it is (see column H)
https://docs.google.com/spreadsheets/d/19EYewR1P759ZRnYNgdFPEPP7zNXzg83iQcRK9hWHAkM/edit#gid=0

3. In the Babanki “List View” we also need to display the new “Plural form” data content as a new line under the elements that are already there. Please activate it in List View. https://livingdictionaries.app/babanki/entries/list

4. Lastly, the Babanki requested a minor revision in the order of elements displayed in each “Entry View”. Please change the elements displayed so they appear like this, from top to bottom. This change to Entry View only applies to Babanki.
Headword
Phonetic
English Gloss
Plural Form (NEW)
Part of Speech
Noun Class
Notes (which will become empty once we transfer the content over to the new data field)

Hope that's ok!! thanks for your help! let me know when it's done because we will need to email them next week.

**Comment by Danble** [comment]
@AnnaLuisaD I'm running late on this because Jacob and I are updating things that need to be done before this, but I can tell you that point number 4 is not going to be possible. The way we structure the code, if we change that will make no sense our code design. I can propose this design: 

Headword
Phonetic
English Gloss
Part of Speech
Plural Form (NEW)
Noun Class
Morphology
Interlinearization
Dialect
Notes

But it must work in every dictionary, not just in one. Since they won't use the last four, the only difference would be `Part of Speech` which necessarily come before the other fields.

**Comment by Danble** [comment]
After Dr. Greg communicated with Pius, the latter agreed the order is not a core feature, so I'll ignore the fourth point.
