### ISSUE TITLE
"Next" button is not working on desktop (urgent)

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#51]
When a user clicks on "Add an Entry" and adds the headword and gloss, then wishes to proceed to the next step, the "Next" button is not functioning on desktop. Nothing happens when they click on it, and the word does not appear to be added to the Entries List. This is quite urgent for dictionary managers wishing to add content to their dictionaries.

On mobile view, this button is working well! I just tested it on my phone.

<img width="1137" alt="Screen Shot 2021-10-07 at 12 30 02 PM" src="https://user-images.githubusercontent.com/17869080/136426377-4502f0b4-df50-4ca3-bb49-9998dac843d7.png">

**Comment by Danble** [comment]
That's right! It is happening both on mobile and on desktop devices. To replicate the issue on desktop I had to leave inactive my livingdictionaries.app for less than 10 minutes. When I went back and write on the lexeme field and then press the "next" button, it seems that nothing happens due to the next page never comes but, in fact, the data is being sent to the database and each time you press the "next" button, the same entry will be saved the same number of times. There's no visible errors on console:
![image](https://user-images.githubusercontent.com/43384963/136636438-562e6704-11e5-4753-bf2e-0e786c6271be.png)
After a little while this error appears:
![image](https://user-images.githubusercontent.com/43384963/136636702-adf2c9c1-3e8a-481c-b300-6fa27f602e23.png)
I think is something related with the offline mode. I don't have any idea of how to face this problem @jacobbowdoin

**Comment by AnnaLuisaD** [comment]
thanks!


*Anna Luisa Daigneault, M.Sc**Program Director,* Living Tongues Institute
for Endangered Languages
phone: +1 (415) 613-0795     email: ***@***.***
web: www.livingtongues.org

*Donate to Living Tongues <https://livingtongues.org/how-to-help/support/>:
*
*Help us protect linguistic diversity*Living Dictionaries
<https://livingdictionaries.app/>*: **An online dictionary-builder for
endangered languages*

___________________________________
*Upcoming Zoom Tutorials about Living Dictionaries *

November 4th, 2021 at 11AM EST (UTC-04:00)

December 2nd, 2021 at 11AM EST (UTC-04:00)
*RSVP to attend
<https://us02web.zoom.us/meeting/register/tZYqce2trD0uEtGLB8UVRmnhg_-AqhpITdp0>*
