### ISSUE TITLE
"About" section difficulties

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#69]
I encounter some difficulties when trying to edit an "About" section in a dictionary. This happened to me during the latest webinar as well. After some refreshing and waiting, sometimes the content is saved onto the page. Other times it disappears. Here is an example from trying to edit the "About" page on the Chamalal Living Dictionary

https://livingdictionaries.app/chamalal/about

<img width="1820" alt="Screen Shot 2021-11-10 at 8 32 08 AM" src="https://user-images.githubusercontent.com/17869080/141122431-7b1ea2a5-14f5-4bdb-b00c-6a48abc55729.png">
<img width="1817" alt="Screen Shot 2021-11-10 at 8 32 59 AM" src="https://user-images.githubusercontent.com/17869080/141122433-6ef4004e-bebd-4a76-829c-86806cbb14d0.png">

**Comment by Danble** [comment]
@jacobbowdoin I think I have found where's the problem:
![image](https://user-images.githubusercontent.com/43384963/142080673-fa5a3eab-a9ce-40b3-8f95-093e61228a30.png)
Since we are fetching (prefetching in this case) something that could or could not exist, when it doesn't it launches a 404 error (underlined part is the problem), and maybe this causes other unexpected issues. 
The same happens in the about page. 
How can I change this in order to only make the request when something is guaranteed to return as a response?

**Comment by AnnaLuisaD** [comment]
interesting issue! I see now why that could be problematic.

**Comment by jacobbowdoin** [comment]
Fixed
